<?php

return [
    'app' => [
        'name' => 'Winter CMS',
        'tagline' => 'Asrlarga qaytish',
    ],
    'locale' => [
        'ar' => 'عربى',
        'be' => 'Беларуская',
        'bg' => 'Болгар',
        'ca' => 'Katalan',
        'cs' => 'Чех',
        'da' => 'Датча',
        'en' => 'Ingliz (Amerika Qo\'shma Shtatlar)',
        'en-au' => 'Ingliz (Avstraliya)',
        'en-ca' => 'Ingliz (Kanada)',
        'en-gb' => 'Ingliz (Britaniya)',
        'et' => 'Eston',
        'de' => 'Nemis',
        'el' => 'Yunon',
        'es' => 'Ispan',
        'es-ar' => 'Ispan (Argentina)',
        'fa' => 'Fors',
        'fr' => 'Fransuz',
        'fr-ca' => 'Fransuz (Kanada)',
        'hu' => 'Vengr',
        'id' => 'Bahasa Indonesia',
        'it' => 'Italiyan',
        'ja' => 'Yapon',
        'kr' => 'Koreys',
        'lt' => 'Litva',
        'lv' => 'Latviya',
        'nb-no' => 'Norvegiya (Bokmål)',
        'nl' => 'Niderland',
        'pl' => 'Polyak',
        'pt-br' => 'Portugal (Braziliya)',
        'pt-pt' => 'Portugal (Portugaliya)',
        'ro' => 'Rumyn',
        'rs' => 'Serb',
        'ru' => 'Rus',
        'fi' => 'Fin',
        'sv' => 'Shved',
        'sk' => 'Slovak',
        'sl' => 'Sloven',
        'th' => 'Tay',
        'tr' => 'Turk',
        'uk' => 'Ukraina',
        'zh-cn' => 'Xitoy (soddalashtirilgan)',
        'zh-tw' => 'Xitoy (tradicional)',
        'vn' => 'Vietnam',
    ],
    'directory' => [
        'create_fail' => 'Katalog yaratib bo\'lmadi: :name',
    ],
    'file' => [
        'create_fail' => 'Fayl yaratib bo\'lmadi: :name',
    ],
    'combiner' => [
        'not_found' => "Resurslar kombayneri ':name' faylini topa olmayapti.",
    ],
    'system' => [
        'name' => 'Tizim',
        'menu_label' => 'Tizim',
        'categories' => [
            'cms' => 'CMS',
            'misc' => 'Boshqa',
            'logs' => 'Yozuvlar',
            'mail' => 'Pochta',
            'shop' => 'Do\'kon',
            'team' => 'Jamoa',
            'users' => 'Foydalanuvchilar',
            'system' => 'Tizim',
            'social' => 'Ijtimoiy',
            'backend' => 'Backend',
            'events' => 'Voqealar',
            'customers' => 'Mijozlar',
            'my_settings' => 'Mening sozlamalarim',
            'notifications' => 'Bildirishnomalar',
        ],
    ],'theme' => [
        'label' => 'Mavzu',
        'unnamed' => 'Nomas mavzu',
        'name' => [
            'label' => 'Mavzu nomi',
            'help' => 'Mavzu nomi unikal kodi bo\'yicha. Masalan, Qish.Vanil',
        ],
    ],
    'themes' => [
        'install' => 'Mavzularni o\'rnatish',
        'search' => 'o\'rnatish uchun mavzularni qidirish...',
        'installed' => 'O\'rnatilgan mavzular',
        'no_themes' => 'Do\'konidan o\'rnatilgan mavzular yo\'q.',
        'recommended' => 'Tavsiya etilgan',
        'remove_confirm' => 'Tanlangan mavzuni olib tashlashga ishonchingiz komilmi?',
    ],
    'plugin' => [
        'label' => 'Plagin',
        'unnamed' => 'Nomi yo\'q plagin',
        'name' => [
            'label' => 'Plagin nomi',
            'help' => 'Plagin nomini unikal kodi bilan kiriting. Masalan, Qish.Blog',
        ],
        'by_author' => ':name tomonidan yaratildi',
    ],
    'plugins' => [
        'manage' => 'Plaginlarni boshqarish',
        'install' => 'Plaginlarni o\'rnatish',
        'install_products' => 'Kengaytmalar o\'rnatish',
        'search' => 'o\'rnatish uchun plaginlarni qidirish...',
        'installed' => 'O\'rnatilgan plaginlar',
        'no_plugins' => 'Do\'konidan o\'rnatilgan plaginlar yo\'q.',
        'recommended' => 'Tavsiya etilgan',
        'plugin_label' => 'Plagin',
        'unknown_plugin' => 'Plagin fayl tizimidan o\'chirilgan.',
        'select_label' => 'Amalni tanlang...',
        'bulk_actions_label' => 'Jamlanma harakatlar',
        'check_yes' => 'Ha',
        'check_no' => 'Yo\'q',
        'unfrozen' => 'Yangilanishlar yoqilgan',
        'enabled' => 'Plagin yoqilgan',
        'freeze' => 'o\'chirish yangilanishlarni',
        'unfreeze' => 'yoqish yangilanishlarni',
        'enable' => 'yoqish',
        'disable' => 'o\'chirish',
        'refresh' => 'qayta yuklash',
        'remove' => 'O\'chirish',
        'freeze_label' => 'Yangilanishlarni o\'chirish',
        'unfreeze_label' => 'Yangilanishlarni yoqish',
        'enable_label' => 'Plaginlarni yoqish',
        'disable_label' => 'Plaginlarni o\'chirish',
        'refresh_label' => 'Plagin ma\'lumotlarini qayta yuklash',
        'action_confirm' => 'Siz haqiqatan ham tanlangan plaginlarni :action qilmoqchimisiz?',
        'freeze_success' => 'Tanlangan plaginlarning yangilanishlari muvaffaqiyatli o\'chirildi.',
        'unfreeze_success' => 'Tanlangan plaginlarning yangilanishlari muvaffaqiyatli yoqildi.',
        'enable_success' => 'Tanlangan plaginlar muvaffaqiyatli yoqildi.',
        'disable_success' => 'Tanlangan plaginlar muvaffaqiyatli o\'chirildi.',
        'refresh_confirm' => 'Siz tanlangan plaginlarning ma\'lumotlarini qayta yuklashni istaysizmi? Bu har bir plaginni ma\'lumotlarini qayta tiklash va uning asosiy holatiga qaytaradi.',
        'refresh_success' => 'Tanlangan plaginlar muvaffaqiyatli yangilandi.',
        'remove_confirm' => 'Siz tanlangan plaginlarni olib tashlashni istaysizmi? Bu ham bir qatorda uning bog\'liq ma\'lumotlarini o\'chiradi.',
        'remove_success' => 'Tanlangan plaginlar muvaffaqiyatli o\'chirildi.',
        'replace' => [
            'multi_install_error' => 'Hozircha bir nechta plaginlarni almashtirish qo\'llab-quvvatlanmaydi',
        ],
    ],
    'project' => [
        'name' => 'Loyiha',
        'owner_label' => 'Egasi',
        'attach' => 'Loyihani ulanish',
        'detach' => 'Loyihani ajratish',
        'none' => 'Topilmadi',
        'id' => [
            'label' => 'Loyiha identifikatori',
            'help' => 'O\'zingizning loyihangiz identifikatorini qanday topish',
            'missing' => 'Foydalanish uchun iltimos, loyihangiz identifikatorini ko\'rsating.',
        ],
        'detach_confirm' => 'Haqiqatan ham ushbu loyihani ajratishni istaysizmi?',
        'unbind_success' => 'Loyiha muvaffaqiyatli ajratildi.',
    ],
    'settings' => [
        'menu_label' => 'Sozlamalar',
        'not_found' => 'Ko\'rsatilgan sozlamalar topilmadi.',
        'missing_model' => 'Sozlamalar sahifasida model haqida ma\'lumot yo\'q.',
        'update_success' => ':name uchun sozlamalar muvaffaqiyatli yangilandi.',
        'test_subject' => 'Pochta test xabari',
        'test_content' => 'Bu pochta test xabari - sizning pochta sozlamalaringiz ishlayotganligini tekshirish uchun.',
        'test_confirm' => 'Bu hozirgi sozlamalaringizni saqlaydi va test xabarini :email manziliga yuboradi.',
        'return' => 'Tizim sozlamalariga qaytish',
        'search' => 'Qidirish',
    ],
    'mail' => [
        'log_file' => 'Yozuv jurnal fayli',
        'menu_label' => 'Pochta sozlamalari',
        'menu_description' => 'Elektron pochta sozlamalarini boshqarish.',
        'general' => 'Umumiy',
        'method' => 'Metod',
        'sender_name' => 'Yuboruvchi nomi',
        'sender_email' => 'Yuboruvchi manzili',
        'php_mail' => 'PHP pochta',
        'smtp' => 'SMTP',
        'smtp_address' => 'SMTP server manzili',
        'smtp_authorization' => 'SMTP avtorizatsiyasidan foydalanish',
        'smtp_authorization_comment' => 'Bu variantni tanlash, agar SMTP serveringiz avtorizatsiya talab etsa.',
        'smtp_username' => 'SMTP foydalanuvchi nomi',
        'smtp_password' => 'SMTP paroli',
        'smtp_port' => 'SMTP porti',
        'smtp_ssl' => 'SSL dan foydalanish',
        'smtp_encryption' => 'SMTP uchun shifrlash protokoli',
        'smtp_encryption_none' => 'Shifrlash yo\'q',
        'smtp_encryption_tls' => 'TLS',
        'smtp_encryption_ssl' => 'SSL',
        'sendmail' => 'Sendmail',
        'sendmail_path' => 'Sendmail yo\'lak',
        'sendmail_path_comment' => 'Iltimos, sendmail yo\'li ni ko\'rsating.',
        'drivers_hint_content' => 'Qo\'llab-quvvatlangan boshqa pochta usullari va ularga qo\'shish yo\'llanmasini ko\'rish uchun <a href=":url" target="_blank">hujjatlariga</a> murojaat qiling.',
    ],
    'mail_templates' => [
        'menu_label' => 'Pochta shablonlari',
        'menu_description' => 'Foydalanuvchilarga va administratorlarga yuboriladigan xat shablonlarini o\'zgartirish.',
        'new_template' => 'Yangi shablon',
        'new_layout' => 'Yangi shablon',
        'new_partial' => 'Yangi qism',
        'template' => 'Shablon',
        'templates' => 'Shablonlar',
        'partial' => 'Qism',
        'partials' => 'Qism',
        'menu_layouts_label' => 'Pochta shablonlari',
        'menu_partials_label' => 'Pochta qismlari',
        'layout' => 'Shablon',
        'layouts' => 'Shablonlar',
        'no_layout' => '-- Shablon yo\'q --',
        'name' => 'Nomi',
        'name_comment' => 'Ushbu shablonni aniqlash uchun foydalaniladigan unikal ism',
        'code' => 'Kod',
        'code_comment' => 'Ushbu shablonni aniqlash uchun foydalaniladigan unikal kod',
        'subject' => 'Mavzu',
        'subject_comment' => 'Xabar mavzusi',
        'description' => 'Tavsif',
        'content_html' => 'HTML',
        'content_css' => 'CSS',
        'content_text' => 'Oddiy matn',
        'test_send' => 'Sinov xabari yuborish',
        'test_success' => 'Sinov xabari muvaffaqiyatli yuborildi.',
        'test_confirm' => 'Sinov xabari :email manziliga yuboriladi. Davom etasizmi?',
        'creating' => 'Yaratilmoqda...',
        'creating_layout' => 'Shablon yaratilmoqda...',
        'saving' => 'Saqlanmoqda...',
        'saving_layout' => 'Shablon saqlanmoqda...',
        'delete_confirm' => 'Haqiqatan ham ushbu ma\'lumotni o\'chirishni istaysizmi?',
        'delete_layout_confirm' => 'Haqiqatan ham ushbu shablonni o\'chirishni istaysizmi?',
        'deleting' => 'O\'chirilmoqda...',
        'deleting_layout' => 'Shablon o\'chirilmoqda...',
        'sending' => 'Sinov xabari yuborilmoqda...',
        'return' => 'Shablonlar ro\'yxatiga qaytish',
        'options' => 'Variantlar',
        'disable_auto_inline_css' => 'Avtomatik ichki CSS-ni o\'chirish',
    ],
    'mail_brand' => [
        'menu_label' => 'Pochta brendingi',
        'menu_description' => 'Pochta shablonlarining ranglarini va tashqi ko\'rinishini o\'zgartiring.',
        'page_title' => 'Pochta tashqi ko\'rinishini sozlash',
        'sample_template' => [
            'heading' => 'Sarlavha',
            'paragraph' => 'Bu abzas, Lorem Ipsum matni va havola o\'z ichiga oladi. Cumque dicta <a>doloremque eaque</a>, enim error laboriosam pariatur possimus tenetur veritatis voluptas.',
            'table' => [
                'item' => 'Element',
                'description' => 'Tavsif',
                'price' => 'Narx',
                'centered' => 'Markazga qarab',
                'right_aligned' => 'O\'ngga moslangan',
            ],
            'buttons' => [
                'primary' => 'Asosiy tugma',
                'positive' => 'Ijobiy tugma',
                'negative' => 'Salbiy tugma',
            ],
            'panel' => 'Bu panel qanday chiroyli?',
            'more' => 'Yana bir matn',
            'promotion' => 'Kupon kodi: YOZ',
            'subcopy' => 'Bu xatning quyi qismi',
            'thanks' => 'Rahmat',
        ],
        'fields' => [
            '_section_background' => 'Orqa fon',
            'body_bg' => 'Hujjatning tana fon',
            'content_bg' => 'Kontent qoplamasining fon',
            'content_inner_bg' => 'Kontent fon',
            '_section_buttons' => 'Tugmalar',
            'button_text_color' => 'Tugma matni rangi',
            'button_primary_bg' => 'Asosiy tugma rangi',
            'button_positive_bg' => 'Ijobiy tugma rangi',
            'button_negative_bg' => 'Salbiy tugma rangi',
            '_section_type' => 'Tipografiya',
            'header_color' => 'Sarlavha rangi',
            'heading_color' => 'Sarlavha ranglari',
            'text_color' => 'Matn rangi',
            'link_color' => 'Havola rangi',
            'footer_color' => 'Pastki kalontitul',
            '_section_borders' => 'Cheklovlar',
            'body_border_color' => 'Sarlavhaning pastki cheklovi rangi',
            'subcopy_border_color' => 'Pastki kalontitulning yuqori cheklovi rangi',
            'table_border_color' => 'Jadvalning cheklovi rangi',
            '_section_components' => 'Komponentlar',
            'panel_bg' => 'Panel fon',
            'promotion_bg' => 'Promo blokning fon',
            'promotion_border_color' => 'Promo blokning cheklovi rangi',
        ],
    ],
    'install'=> [
        'project_label' => 'Loyihaga qo\'shish',
        'plugin_label'=> 'Plagin o\'rnatish',
        'theme_label' => 'Mavzuni o\'rnatish',
        'missing_plugin_name' => 'Iltimos, o\'rnatish uchun plagin nomini kiriting.',
        'missing_theme_name'=> 'Iltimos, o\'rnatish uchun mavzu nomini kiriting.',
        'install_completing'=> 'O\'rnatish jarayoni yakunlanmoqda',
        'install_success' => 'Plagin muvaffaqiyatli o\'rnatildi.',
    ],
    'updates'=> [
        'title'=> 'Yangilanish boshqaruvi',
        'name' => 'Dastur yangilanishlari',
        'menu_label' => 'Yangilanishlar va plaginlar',
        'menu_description' => 'Tizimni yangilash, plaginlarni va mavzularni boshqarish va o\'rnatish.',
        'return_link'=> 'Yangilanishlar tizimiga qaytish',
        'check_label'=> 'Yangilanishlarni tekshirish ',
        'retry_label'=> 'Qayta urinib ko\'ring',
        'plugin_name'=> 'Nomi',
        'plugin_code'=> 'Kodi',
        'plugin_description' => 'Tavsif',
        'plugin_version' => 'Versiya',
        'plugin_author'=> 'Muallif',
        'plugin_not_found' => 'Plagin topilmadi',
        'plugin_version_not_found' => 'Plagin versiyasi topilmadi',
        'core_current_build' => 'Hozirgi qurilma',
        'core_view_changelog'=> 'O\'zgarishlar ro\'yxatini ko\'rish',
        'core_build' => 'Qurilma :build',
        'core_build_help'=> 'So\'nggi mavjud qurilma.',
        'core_downloading' => 'Dastur fayllarini yuklash',
        'core_extracting'=> 'Dastur fayllarini ajratib olish',
        'core_set_build' => 'Qurilma raqamini sozlash',
        'update_warnings_title'=> 'Sizning diqqatingizni talab qiladigan muammolar aniqlandi',
        'update_warnings_plugin_missing' => ':code plagini :parent_code plagining boshqa plaginiga bog\'liq bo\'lib, lekin tizimda topilmadi. Iltimos, ushbu plaginni o\'rnatib ko\'ring.',
        'update_warnings_plugin_replace' => ':plugin plagini :alias ni o\'rnata oladi, uning ishlashini yo\'qotib qo\'ying',
        'update_warnings_plugin_replace_cli' => ':plugin plagini :alias ni o\'rnata oladi, uning ishlashini yo\'qotib qo\'ying',
        'changelog'=> 'O\'zgarishlar ro\'yxati',
        'changelog_view_details' => 'Tafsilotlarni ko\'rish',
        'plugins'=> 'Plaginlar',
        'themes' => 'Mavzular',
        'disabled' => 'O\'chirilgan',
        'plugin_downloading' => 'Plagin yuklanmoqda: :name',
        'plugin_extracting'=> 'Plagin ajratib olinmoqda: :name',
        'plugin_version_none'=> 'Yangi plagin',
        'plugin_current_version' => 'Hozirgi versiya',
        'theme_new_install'=> 'Yangi mavzu o\'rnatildi.',
        'theme_downloading'=> 'Mavzu yuklanmoqda: :name',
        'theme_extracting' => 'Mavzu ajratib olinmoqda: :name',
        'update_label' => 'Yangilash',
        'update_completing'=> 'Yangilash jarayoni yakunlanmoqda',
        'update_loading' => 'Mavjud yangilanishlarni qidirish...',
        'update_success' => 'Yangilash jarayoni muvaffaqiyatli yakunlandi.',
        'update_failed_label'=> 'Yangilash muvaffaqiyatsiz yakunlandi',
        'force_label'=> 'Majburiy yangilash',
        'found'=> [
            'label' => 'Yangi yangilanishlar mavjud!',
            'help'=> 'Yangilash jarayonini boshlash uchun "Yangilash"ni tanlang.',
        ],
        'none' => [
            'label' => 'Yangilanishlar mavjud emas',
            'help'=> 'Yangi yangilanishlar topilmadi.',
        ],
        'important_action' => [
            'empty' => 'Harakatni tanlang',
            'confirm' => 'Yangilashni tasdiqlang',
            'skip'=> 'Ushbu plaginni o\'tkazib yuborish (faqat bir bor)',
            'ignore'=> 'Ushbu plaginni o\'tkazib yuborish (doimiy ravishda)',
        ],
        'important_action_required'=> 'Kerakli harakat',
        'important_view_guide' => 'Yengilash ko\'rsatkichini ko\'rish',
        'important_view_release_notes' => 'E\'lonlarni ko\'rish',
        'important_alert_text' => 'Ba\'zi yangilanishlar sizning diqqatingizni talab qiladi.',
        'details_title'=> 'Plagin ma\'lumotlari',
        'details_view_homepage'=> 'Bosh sahifaga o\'tish',
        'details_readme' => 'Hujjat',
        'details_readme_missing' => 'Hujjat taqdim etilmagan.',
        'details_changelog'=> 'O\'zgarishlar ro\'yxati',
        'details_changelog_missing'=> 'O\'zgarishlar ro\'yxati topilmadi.',
        'details_upgrades' => 'Yengilash qo\'llanmasi',
        'details_upgrades_missing' => 'Yengilash qo\'llanmasi taqdim etilmagan.',
        'details_licence'=> 'Litsenziya',
        'details_licence_missing'=> 'Litsenziya taqdim etilmagan.',
        'details_current_version'=> 'Hozirgi versiya',
        'details_author' => 'Muallif',
    ],
    'server' => [
        'connect_error'=> 'Serverga ulanishda xato.',
        'response_not_found' => 'Yangilanish serveri topilmadi.',
        'response_invalid' => 'Serverning noaniq javobi.',
        'response_empty' => 'Serverning bo\'sh javobi.',
        'file_error' => 'Server paketni yetkazib berishda xato.',
        'file_corrupt' => 'Yuklab olingan fayl zararli.',
    ],
    'behavior' => [
        'missing_property' => ':class sinfi :behavior kengaytmasi tomonidan ishlatiladigan $:property xususiyatini o\'z ichida bo\'lishi kerak.',
    ],
    'config' => [
        'not_found' => ':location uchun kutilgan :file sozlamalar fayli topilmadi.',
        'required'=> ":location uchun sozlanmada ':property' xususiyati aniqlanmagan.",
    ],
    'zip'=> [
        'extract_failed' => "':file' faylni olish mumkin emas.",
    ],
    'event_log'=> [
        'hint' => 'Ushbu jurnaldan, iloji boricha, dastur ishlab chiqish jarayonida yuzaga keladigan xatoliklar, istisno va debug ma\'lumotlarining ro\'yxati ko\'rinadi.',
        'menu_label' => 'Tadbir jurnali',
        'menu_description' => 'Tizim tadbir jurnalini ko\'rish.',
        'empty_link' => 'Tadbir jurnalini tozalash',
        'empty_loading'=> 'Tadbir jurnalini tozalash...',
        'empty_success'=> 'Tadbir jurnali muvaffaqiyatli tozalandi.',
        'return_link'=> 'Tadbir jurnaliga qaytish',
        'id' => 'ID',
        'id_label' => 'Tadbir IDsi',
        'created_at' => 'Sana & Vaqt',
        'message'=> 'Xabar',
        'level'=> 'Daraja',
        'preview_title'=> 'Tadbirlar',
    ],
    'request_log'=> [
        'hint' => 'Bu jurnalda brauzer so\'rovlarining ro\'yxati ko\'rsatiladi, ulardan qanday ehtiyoj bo\'lishi mumkin. Misol uchun, agar tashrifchi mavjud bo\'lmagan sahifani ochsa, jurnalda 404 xolat kodi bilan yozuv yaratiladi.',
        'menu_label' => 'So\'rovlar jurnali',
        'menu_description' => 'Muvaffaqiyatsiz yoki yo\'naltirilgan so\'rovlarni ko\'rish.',
        'empty_link' => 'So\'rovlar jurnalini tozalash',
        'empty_loading'=> 'So\'rovlar jurnalini tozalash...',
        'empty_success'=> 'So\'rovlar jurnali muvaffaqiyatli tozalandi.',
        'return_link'=> 'So\'rovlar jurnaliga qaytish',
        'id' => 'ID',
        'id_label' => 'Yozuv IDsi',
        'count'=> 'Hisoblagich',
        'referer'=> 'So\'rov manbai',
        'url'=> 'Manzil',
        'status_code'=> 'Holat kodi',
        'preview_title'=> 'So\'rov',
    ],
    'permissions'=> [
        'name'=> 'Tizim',
        'manage_system_settings'=> 'Tizim sozlamalarini boshqarish',
        'manage_software_updates' => 'Dasturlash yangilanishlarni boshqarish',
        'access_logs' => 'Tizim jurnalini ko\'rish',
        'manage_mail_templates' => 'Pochta shablonlarini boshqarish',
        'manage_mail_settings'=> 'Pochta sozlamalarini boshqarish',
        'manage_other_administrators' => 'Boshqa administratorlarni boshqarish',
        'impersonate_users' => 'Foydalanuvchilarni qo\'llab-quvvatlash',
        'manage_preferences'=> 'Tizim sozlamalarini boshqarish',
        'manage_editor' => 'Kod tahrirlovchining sozlamalarini boshqarish',
        'manage_own_editor' => 'Shaxsiy kod tahrirlovchining sozlamalarini boshqarish',
        'view_the_dashboard'=> 'Boshqaruv panelini ko\'rish',
        'manage_default_dashboard'=> 'Standart boshqaruv panelini boshqarish',
        'manage_branding' => 'Boshqaruvni shakllantirish',
    ],
    'log'=> [
        'menu_label' => 'Jurnal sozlamalari',
        'menu_description' => 'CMSning qaysi qismlari uchun jurnal olib borish kerakligini belgilang.',
        'default_tab'=> 'Jurnalni boshqarish',
        'log_events' => 'Tizim hodisalarini saqlash',
        'log_events_comment' => 'Tizim hodisalarini fayllar jurnali bilan birgalikda ma\'lumotlar bazasida saqlash.',
        'log_requests' => 'Muvaffaqiyatsiz so\'rovlarini saqlash',
        'log_requests_comment' => 'Brauzer so\'rovlari, foydalanuvchi ehtiyojini talab qila oladiganlar. Masalan, 404 xatolar.',
        'log_theme'=> 'Mavzuni o\'zgartirishni saqlash',
        'log_theme_comment'=> 'CMS vositasida kiritilgan o\'zgartirishlar.',
    ],
    'media'=> [
        'invalid_path'=> "Noto'g'ri fayl yo'li kiritildi: ':path'.",
        'folder_size_items' => 'elementlar',
    ],
    'page' => [
        'custom_error' => [
            'label' => 'Sahifa xatosi',
            'help'=> "Uzr, nima uchun shu sahifa ko'rinmayapti, nima narsa bo'ldi.",
        ],
        'invalid_token' => [
            'label' => 'Noto\'g\'ri xavfsizlik belgisi',
        ],
        'maintenance' => [
            'label'=> "Tez orada qaytadi!",
            'help' => "Hozir biz servis holatida, keyinroq kirib ko'ring!",
            'message'=> 'Xabar:',
            'available_at' => 'Keyinroq qaytadan urinib ko\'ring:',
        ],
    ],
    'pagination' => [
        'previous' => 'Oldingi',
        'next' => 'Keyingi',
    ],
];
